[[ -d ~/.local/bin/ ]] && PATH="$HOME/.local/bin/:$PATH"

source ~/.config/bash/environment.sh

if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

source ~/.config/bash/functions.sh
source ~/.config/bash/alias.sh
